name: Lint
on:
  pull_request:
    branches:
      - main
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn install
      - name: Lint with ESLint
        run: yarn run lint
      - name: Test with Jest
        run: yarn test
